name: Daily Export

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.15"
      - name: Cache python packages
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ runner.os }}-pip-${{ hashFiles('./requirements.txt') }}
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      - name: Run python scripts
        run: |
          python ./src/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Autorun
          file_pattern: '*.csv'